Always pull Docker image
AdoptOpenJDK/ci-jenkins-pipelines pull request #104
Opened 2021-03-19 04:43 UTC by AdamBrousseau

Existing behaviour is to only pull DOCKER_IMAGE when
using the image as is. If the DOCKER_FILE path is
traversed, the base DOCKER_IMAGE is not refreshed
if it exists on the system. Fix is to move the pull
before the 'if' so that it is run for both cases.

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

2021-03-19 05:17 UTC, AdamBrousseau commented
Tested both code paths on my farm, working as expected.

2021-03-19 12:24 UTC, M-Davies requested changes
With this change, does this invalidate the need for the `if` conditional determining if we should check for a `buildConfig.DOCKER_FILE`? If we are always going to pull, do we need to have the logic to build? I am unsure but do we have some images that we always need to build that are not stored on dockerhub? If so, this could be a breaking change for those builds

2021-03-19 12:24 UTC, M-Davies commented on pipelines/build/common/openjdk_build_pipeline.groovy
>                              // Otherwise, pull the docker image from DockerHub
Now an irrelevant comment

2021-03-19 16:16 UTC, AdamBrousseau commented on pipelines/build/common/openjdk_build_pipeline.groovy
>                              // Otherwise, pull the docker image from DockerHub
Moved & adjusted.

2021-03-19 16:24 UTC, AdamBrousseau commented
@M-Davies I can think of 3 use cases but only the first 2 seem to be supported currently
1. Docker image provided
2. Docker image & Docker file provided
3. Docker file provided
 
Based on L1199 the code is written that you must at least supply the image. The use case for a file is when you build an image during the build with a base image `DOCKER_IMAGE`. This is what the OpenJ9 builds do with the addition of cuda". You could build these and store them, eliminating the need to do it in the build. That's a separate topic. But I think the builds should also support the 3rd case of building given only a file which it doesn't appear they do at the moment. But that's also a separate discussion imo. I don't think this PR affects the use cases in any way.

2021-03-19 16:40 UTC, M-Davies approved these changes
Fair enough and [checking the docs, it doesn't look like anything needs to be updated over there](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines#data-fields). Let's give it a try

2021-03-22 15:02 UTC, karianna approved these changes
LGTM

2021-03-22 15:02 UTC, merged