Disable OpenJ9 XL Specs
AdoptOpenJDK/ci-jenkins-pipelines pull request #23
Opened 2021-02-10 18:15 UTC by AdamBrousseau

Turn off large heap platforms in the ci builds.
More cleanup can be done related to xl packages
once the dust settles.

Depends #22

Signed-off-by: Adam Brousseau <adam.brousseau@ca.ibm.com>

2021-02-10 20:15 UTC, karianna approved these changes
LGTM

2021-02-10 20:48 UTC, gdams commented
run-tests

2021-02-10 20:51 UTC, gdams commented
run tests

2021-02-10 21:09 UTC, llxia approved these changes
LGTM

2021-02-10 21:12 UTC, M-Davies requested changes
Can we remove the build config values from the `jdkxx_pipeline_config.groovy` files too?

2021-02-10 21:24 UTC, AdamBrousseau commented
@M-Davies is that needed to disable the builds? I was thinking that would be part of the follow up cleanup.

2021-02-10 21:35 UTC, M-Davies commented
> @M-Davies is that needed to disable the builds? I was thinking that would be part of the follow up cleanup.

Shouldn't they be removed at the same time? It would allow for an easier revert later down the line in case we decide to add XL specs back in?

2021-02-10 21:44 UTC, AdamBrousseau commented
I guess it's up to Adopt. By that argument we should remove all xl related stuff in 1 PR. I don't think there'll be need to revert once the seconds PR cleans up all the xl related code.

2021-02-11 17:22 UTC, AdamBrousseau commented
Can I leave it up to Adopt folks to determine if there are other areas that need changes? Website, API, Docker etc. There will be existing released XL builds but going forward there will only be the default build.

2021-02-11 18:59 UTC, M-Davies approved these changes
I'm ok for improving this for now but we should clarify how to remove and/or disable platforms in the future (preferably in the FAQ)

2021-02-12 11:28 UTC, gdams approved these changes

2021-02-12 11:32 UTC, M-Davies commented
> I'm ok for improving this for now but we should clarify how to remove and/or disable platforms in the future (preferably in the FAQ)

In fact, we [already clarified it](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/blob/master/FAQ.md#how-to-enabledisable-a-particular-build-configuration).

2021-02-16 12:44 UTC, karianna commented
@AdamBrousseau rebase sorry!

2021-02-16 16:26 UTC, AdamBrousseau commented
Rebased. Set as draft until 22 is merged.

2021-02-22 19:06 UTC, gdams commented
@AdamBrousseau can we merge this now?

2021-02-22 19:07 UTC, AdamBrousseau commented
Yes I think we're ready for this.

2021-02-22 19:11 UTC, merged

2021-02-22 19:12 UTC, gdams commented
It would be good to clear up the XL build jobs from the active versions in jenkins. @M-Davies I wonder whether we can modify the generator jobs to cleanup jobs that are no longer defined?