fix generateBuildMatrix.sh
AdoptOpenJDK/ci-jenkins-pipelines pull request #40
Opened 2021-02-16 14:47 UTC by gdams

The generator was broken. The markdown in the current Readme is all over the place

2021-02-16 16:15 UTC, karianna requested changes
The shell script could do with being split into functions where it makes sense and having some comments added to complex lines.

2021-02-23 11:37 UTC, M-Davies approved these changes
Approved as long as Martijn's comment is addressed

2021-03-17 21:23 UTC, karianna commented
@gdams rebase required (if splitting out functions is too hard this PR then lets open a new issue for that)

2021-03-28 12:50 UTC, karianna approved these changes

2021-03-28 12:51 UTC, merged