Rename RepoHandler Functions
AdoptOpenJDK/ci-jenkins-pipelines pull request #42
Opened 2021-02-17 13:15 UTC by M-Davies

* Updates the user scripts and defaults to account for the recent code split

Signed-off-by: Morgan Davies <morgandavies2020@gmail.com>

2021-02-17 22:03 UTC, M-Davies commented
run tests

2021-02-17 22:22 UTC, M-Davies commented
run tests

2021-02-17 22:36 UTC, M-Davies commented
run tests

2021-02-17 22:41 UTC, M-Davies commented
run tests

2021-02-17 22:46 UTC, M-Davies commented
run tests

2021-02-17 22:57 UTC, M-Davies commented
run tests

2021-02-17 23:04 UTC, M-Davies commented
run tests

2021-02-18 16:43 UTC, M-Davies commented
I realise now the PR tester will fail as it hasn't been merged yet 🤦 I'll try and figure out a way to test this alternatively

2021-02-18 17:27 UTC, karianna commented on pipelines/build/common/build_base_file.groovy
> +            if (javaToBuild == "jdk${getHeadVersionNumber()}") {
Add comment to highlight what this special case is doing

2021-02-18 23:39 UTC, karianna commented
@M-Davies compilation failure?

2021-02-19 09:30 UTC, M-Davies commented
The `RepoHandlerTest` should be resolved upon merge. The `context.timeout(time: pipelineTimeouts.API_REQUEST_TIMEOUT, unit: "HOURS") {` are unrelated to this PR and generally caused by https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/issues/14

2021-02-19 11:08 UTC, karianna approved these changes

2021-02-19 11:57 UTC, andrew-m-leonard requested changes

2021-02-19 11:57 UTC, andrew-m-leonard commented on pipelines/library/src/common/RepoHandler.groovy
>      public void checkoutAdopt () {
I think these 3 functions could be named better? say:
checkoutAdoptPipelines()
checkoutUserPipelines()
checkoutAdoptBuild()

2021-02-19 12:00 UTC, andrew-m-leonard commented on pipelines/build/common/openjdk_build_pipeline.groovy
> +                                context.println "[INFO] Executing user shell scripts..."
Not sure the build-farm/make-adopt-build-farm.sh is going to be found as checkoutUser() checks out user pipelines repo, not a user build repo?

2021-02-19 14:15 UTC, M-Davies commented
run tests

2021-02-19 19:40 UTC, andrew-m-leonard approved these changes
I think it's ok, although still a bit confused over checkouts... assuming tested ok, lets give it a try...

2021-02-22 13:10 UTC, M-Davies commented
Probably a bit late to merge this today as I'm about to sign off. I'll look into merging tomorrow morning

2021-02-23 08:46 UTC, M-Davies commented
Draft while ongoing external issues are being resolved

2021-02-23 09:12 UTC, M-Davies commented on pipelines/library/src/common/RepoHandler.groovy
> +    public void checkoutUserBuild () {
TODO: Open an issue after merging to make this configurable by the constructor and class level

2021-02-23 09:39 UTC, M-Davies commented
Merging and running a test pipeline and generation

2021-02-23 09:39 UTC, merged